# Generated by Django 4.2.4 on 2023-08-25 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Univ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("univName", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickName", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(default="", max_length=100, unique=True)),
                (
                    "univ_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.univ"
                    ),
                ),
            ],
        ),
    ]
